version: "3.8"
services:
  ssh-testserver-01:
    image: ghcr.io/linuxserver/openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London     
      - USER_PASSWORD=password #optional     
      - USER_NAME=admin #optional    
      - PASSWORD_ACCESS=true
    ports:
      - 2222:2222

  boundary-terraform-provisioning:
    build:
      context: ./provisioning-terraform
    entrypoint: []
    command: /bin/sh -c '/wait-for.sh boundary:9200 -- terraform -chdir=/scripts apply -auto-approve'
    depends_on:      
      - "boundary"

  ## Necessary unitl Terraform implements new OIDC Auth Method!
  boundary-script-provisioning:
    build:
      context: ./provisioning-script
    entrypoint: []
    command: /bin/sh -c '/wait-for.sh boundary:9200 -- /scripts/provision-oidc.sh'
    depends_on:
      - "boundary-terraform-provisioning"
      - "boundary"

  boundary-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
    volumes:
      - ./keycloak/realm.json:/tmp/realm.json
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.profile.feature.scripts=enabled"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"

