version: "3.8"
services:
 
  boundary:
    image: hashicorp/boundary  
    ports:
      - 9200:9200
      - 9201:9201
      - 9202:9202 
    environment:
      BOUNDARY_POSTGRES_URL: postgresql://postgres:postgres@boundary-db:5432/postgres?sslmode=disable
    command: "dev -log-level='info' -recovery-key='evxLxhixAwXp+jayjvuSNPbyak4keFw34XMtrt7l5Mo=' -host-address='0.0.0.0' -api-listen-address='0.0.0.0' -proxy-listen-address='0.0.0.0' -worker-public-address='0.0.0.0' -controller-public-cluster-address='0.0.0.0' -cluster-listen-address='0.0.0.0' -login-name='admin' -password='admin123456' -database-url='postgresql://postgres:postgres@boundary-db:5432/postgres?sslmode=disable'"
    depends_on:
      boundary-db:
        condition: service_healthy
